## "sudo: true" environment is much slower than the "sudo: false" environment even though it provides larger memory.
sudo: false
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
    packages:
      - libxerces-c-dev
      - ninja-build
      - clang++-3.9
      - g++-6

cache: pip
before_install:
  - git clone -b cmake --depth 1 git://github.com/huangminghuang/ACE_TAO.git
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      mkdir $HOME/usr;
      export PATH="$HOME/usr/bin:$PATH";
      wget --no-check-certificate https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh;
      chmod +x cmake-3.7.2-Linux-x86_64.sh;
      ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license;
    fi
  - pip install --user awscli

branches:
  only:
    - cmake

before_script:
  - export
  - if [ "$FUZZ" == "1" ]; then
        tar czf modeling_plugins.tar.gz tools/modeling/plugins;
        rm -rf tools/modeling/plugins tools/IntermediateTypeLang/cpp/rapidjson;
        perl $DDS_ROOT/tools/scripts/dds_fuzz.pl;
        tar xzf modeling_plugins.tar.gz;
        rm modeling_plugins.tar.gz;
    fi
  - if [ "$INLINE" == "0" ]; then DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DACE_INLINE=OFF"; fi
  - if [ "$BIT" == "0" ]; then DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DOPENDDS_HAS_BUILT_IN_TOPICS=OFF"; fi
  - if [ "$STATIC" == "1" ]; then DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DBUILD_SHARED_LIBS=OFF"; fi
  - if [ "$DEBUG" == "0" ]; then
      DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DCMAKE_BUILD_TYPE=RELEASE";
    else
      DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DCMAKE_BUILD_TYPE=DEBUG";
    fi
  - if [ "$SAFETY_PROFILE" == "1" ]; then
         DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DOPENDDS_SAFETY_PROFILE=BASE";
    fi
  - if [ "$USES_WCHAR" == "1" ]; then DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DACE_USES_WCHAR=ON"; fi
  ## we need to disable ccahe explicitly because it is installed in the travis ci environment but the environment
  ## does not have enough disk space to cache all OpenDDS object code
  - export DDS_BUILD_FLAGS="$DDS_BUILD_FLAGS -DACE_TAO_SOURCE_DIR=$TRAVIS_BUILD_DIR/ACE_TAO -DCCACHE_PROGRAM=OFF"

jobs:
  include:
    - stage: build
      script: ./travis_build.sh Debug
      env: DEBUG=0 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh Release
      env: DEBUG=1 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh NoInline
      env: INLINE=0 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh NoBit
      env: BIT=0 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh Static
      ## static debug build would cause out of disk space error on travis ci
      env: STATIC=1 DEBUG=0 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh SafetyProfile
      env: SAFETY_PROFILE=1 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh WChar
      env: USE_WCHAR=1 COMPILER=g++-6
    - stage: build
      script: ./travis_build.sh Clang
      env: COMPILER=clang++-3.9
    - stage: test
      script: ./travis_run_tests.sh Debug
      env: DEBUG=0 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh Release
      env: DEBUG=1 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh NoInline
      env: INLINE=0 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh NoBit
      env: Bit=0 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh Static
      env: STATIC=1 DEBUG=0 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh SafetyProfile
      env: SAFETY_PROFILE=1 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh WChar
      env: USE_WCHAR=1 COMPILER=g++-6
    - stage: test
      script: ./travis_run_tests.sh Clang
      env: COMPILER=clang++-3.9